name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
